import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        md: "2rem",
      },
      screens: {
        "2xl": "1280px",
      },
    },
    extend: {
      colors: {
        ink: "rgb(var(--tax-ink-rgb) / <alpha-value>)",
        "iris-teal": "rgb(var(--palette-slate-rgb) / <alpha-value>)",
        brass: {
          DEFAULT: "rgb(var(--palette-coral-rgb) / <alpha-value>)",
          light: "rgb(var(--palette-coral-rgb) / <alpha-value>)",
          subtle: "rgb(var(--palette-coral-rgb) / 0.12)",
        },
        paper: {
          DEFAULT: "rgb(var(--tax-paper-rgb) / <alpha-value>)",
          light: "rgb(var(--tax-paper-light-rgb) / <alpha-value>)",
        },
        folio: "rgb(var(--tax-folio-rgb) / <alpha-value>)",
        rule: {
          DEFAULT: "rgb(var(--tax-rule-rgb) / <alpha-value>)",
          light: "rgb(var(--tax-rule-rgb) / 0.12)",
        },
        "stamp-red": "rgb(var(--palette-coral-rgb) / <alpha-value>)",
        ash: {
          DEFAULT: "rgb(var(--tax-ash-rgb) / <alpha-value>)",
          light: "rgb(var(--tax-ash-light-rgb) / <alpha-value>)",
        },
        accent: {
          DEFAULT: "rgb(var(--palette-coral-rgb) / <alpha-value>)",
          strong: "rgb(var(--palette-coral-hover-rgb) / <alpha-value>)",
          surface: "rgb(var(--palette-coral-rgb) / 0.14)",
        },
        apple: {
          blue: "rgb(var(--apple-blue-rgb) / <alpha-value>)",
          indigo: "rgb(var(--apple-indigo-rgb) / <alpha-value>)",
          purple: "rgb(var(--apple-purple-rgb) / <alpha-value>)",
          pink: "rgb(var(--apple-pink-rgb) / <alpha-value>)",
          red: "rgb(var(--apple-red-rgb) / <alpha-value>)",
          orange: "rgb(var(--apple-orange-rgb) / <alpha-value>)",
          yellow: "rgb(var(--apple-yellow-rgb) / <alpha-value>)",
          green: "rgb(var(--apple-green-rgb) / <alpha-value>)",
          mint: "rgb(var(--apple-mint-rgb) / <alpha-value>)",
          teal: "rgb(var(--apple-teal-rgb) / <alpha-value>)",
          cyan: "rgb(var(--apple-cyan-rgb) / <alpha-value>)",
          gray: "rgb(var(--apple-gray-rgb) / <alpha-value>)",
          gray2: "rgb(var(--apple-gray2-rgb) / <alpha-value>)",
          gray3: "rgb(var(--apple-gray3-rgb) / <alpha-value>)",
          gray4: "rgb(var(--apple-gray4-rgb) / <alpha-value>)",
          gray5: "rgb(var(--apple-gray5-rgb) / <alpha-value>)",
          gray6: "rgb(var(--apple-gray6-rgb) / <alpha-value>)",
        },
        system: {
          bg: "rgb(var(--system-bg-rgb) / <alpha-value>)",
          "grouped-bg": "rgb(var(--system-grouped-bg-rgb) / <alpha-value>)",
          card: "rgb(var(--system-card-rgb) / <alpha-value>)",
          label: "rgb(var(--system-label-rgb) / <alpha-value>)",
          "secondary-label": "rgb(var(--system-secondary-label-rgb) / <alpha-value>)",
          separator: "rgb(var(--system-separator-rgb) / <alpha-value>)",
          tint: "rgb(var(--system-tint-rgb) / <alpha-value>)",
        },
        palette: {
          slate: "rgb(var(--palette-slate-rgb) / <alpha-value>)",
          sky: "rgb(var(--palette-sky-rgb) / <alpha-value>)",
          frost: "rgb(var(--palette-frost-rgb) / <alpha-value>)",
          coral: "rgb(var(--palette-coral-rgb) / <alpha-value>)",
          gunmetal: "rgb(var(--palette-gunmetal-rgb) / <alpha-value>)",
        },
        theme: {
          primary: "var(--theme-primary)",
          "primary-hover": "var(--theme-primary-hover)",
          surface: "var(--theme-surface)",
          "surface-raised": "var(--theme-surface-raised)",
          background: "var(--theme-background)",
          text: "var(--theme-text)",
          "text-secondary": "var(--theme-text-secondary)",
          "text-muted": "var(--theme-text-muted)",
          border: "var(--theme-border)",
          accent: "var(--theme-accent)",
          success: "var(--theme-success)",
          danger: "var(--theme-danger)",
          glass: "var(--theme-glass-bg)",
          "glass-border": "var(--theme-glass-border)",
        },
      },
      borderRadius: {
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
      },
      fontFamily: {
        sans: [
          "-apple-system",
          "BlinkMacSystemFont",
          '"SF Pro Text"',
          '"SF Pro"',
          "var(--font-inter)",
          "Inter",
          "system-ui",
          '"Helvetica Neue"',
          "Helvetica",
          "Arial",
          "sans-serif",
        ],
        serif: [
          '"New York"',
          '"SF Pro Display"',
          "-apple-system-ui-serif",
          "ui-serif",
          "Georgia",
          '"Times New Roman"',
          "Times",
          "serif",
        ],
        display: [
          '"SF Pro Display"',
          "-apple-system",
          "BlinkMacSystemFont",
          "var(--font-inter)",
          "Inter",
          "system-ui",
          "sans-serif",
        ],
        mono: [
          "ui-monospace",
          '"SF Mono"',
          '"SFProMono-Regular"',
          "Menlo",
          "Monaco",
          "Consolas",
          '"Liberation Mono"',
          '"Courier New"',
          "monospace",
        ],
        rounded: [
          "ui-rounded",
          '"SF Pro Rounded"',
          "-apple-system",
          "BlinkMacSystemFont",
          "sans-serif",
        ],
        urdu: ["var(--font-urdu)", '"Noto Nastaliq Urdu"', "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
